version: '2.4'

services:
  db:
    image: mariadb
    restart: always
    command: --skip-innodb-read-only-compressed --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - "./db:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=<root password>
      - MYSQL_PASSWORD=<password>
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  redis:
    image: redis:alpine
    restart: always

  app:
    build: .
    restart: always
    ports:
      - 8080:80
    volumes:
      - nextcloud:/var/www/html
      - "./apps:/var/www/html/custom_apps"
      - "./config:/var/www/html/config"
      - "./data:/var/www/html/data"
    environment:
      - VIRTUAL_HOST=<your domain>
      - LETSENCRYPT_HOST=<your domain>
      - LETSENCRYPT_EMAIL=<your email>
      - MYSQL_PASSWORD=<db password>
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
    networks:
      - proxy-tier
      - default

  cron:
    build: .
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - "./apps:/var/www/html/custom_apps"
      - "./config:/var/www/html/config"
      - "./data:/var/www/html/data"
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

  proxy:
    build: ./proxy
    restart: always
    environment:
      - ENABLE_IPV6=true
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - acme:/etc/acme.sh
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - proxy

  ddns-route53:
    image: crazymax/ddns-route53:latest
    container_name: ddns-route53
    environment:
      - "TZ=Asia/Shanghai"
      - "SCHEDULE=*/30 * * * *"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
      - "DDNSR53_CREDENTIALS_ACCESSKEYID=<access key id>"
      - "DDNSR53_CREDENTIALS_SECRETACCESSKEY=<secret access key>"
      - "DDNSR53_ROUTE53_HOSTEDZONEID=<host zone id>"
      - "DDNSR53_ROUTE53_RECORDSSET_0_NAME=<domain name>"
      - "DDNSR53_ROUTE53_RECORDSSET_0_TYPE=<AAAA for IPv6, A for IPv4>"
      - "DDNSR53_ROUTE53_RECORDSSET_0_TTL=300"
    restart: always
    networks:
      - proxy-tier
        
volumes:
  nextcloud:
  certs:
  acme:
  vhost.d:
  html:

networks:
  proxy-tier:
    enable_ipv6: true
    ipam:
      config:
        - subnet: "fd00:dead:beef::/48"
